@{
	MODULEVERSION = '1.0'
	GUID = '5E17DDDE-1F9E-4B59-8070-2D118F47E283'
	AUTHOR = 'TOM NOLAN'
	COMPANYNAME = 'TINYINT.COM'
	COPYRIGHT = '(C) 2015 TOM NOLAN. ALL RIGHTS RESERVED.'
	DESCRIPTION = 'THIS IS A POWERSHELL MODULE TO INTERFACE WITH SHOUTCLOUD.IO'
	NESTEDMODULES = "PSSHOUTCLOUD.PSM1"
	FUNCTIONSTOEXPORT = "*"
	FILELIST = @("PSSHOUTCLOUD.PSD1", "PSSHOUTCLOUD.PSM1", "README.md", "LICENSE")
}

